### ISSUE TITLE
Integration needs to be reloaded after inverter goes offline

### ISSUE THREAD

**Issue by krisdieteren** [zbigniewmotyka/home-assistant-solplanet#14]
My inverter (ASW6K-LT-G2 Pro) goes offline each evening. If I don’t reload the integration in the morning after it is online again, the sensors remain unavailable. 

Is it possible to reload automatically?

**Comment by blasteris** [comment]
I have the same problem with my (ASW25K-LT-G3) inverter, thou I don't need to reload every morning.

**Comment by krisdieteren** [comment]
Sometimes it runs for a few days, but I have not found a logic in it yet.

**Comment by tomz71** [comment]
Same here with ASW6K-LT-G2 Pro inverter. It works for few days without issue, but sometimes it needs to reload.

**Comment by blasteris** [comment]
I think this happens when solar panels stop producing energy and inverter goes to sleep and while it is in sleep mode you reload or restart HA. After restart it stops detecting sensors.  I created automation to reload config entry 25min after sunrise.

**Comment by tomz71** [comment]
> I think this happens when solar panels stop producing energy and inverter goes to sleep and while it is in sleep mode you reload or restart HA. After restart it stops detecting sensors. I created automation to reload config entry 25min after sunrise.

Yes, it makes sense, worked whole week without problems, yesterday night i have configured and restarted the HA, and today morning it was offline. Thanks for the light-up! :)

**Comment by zbigniewmotyka** [comment]
Can you attach logs for Solplanet integration?

**Comment by krisdieteren** [comment]
Also from me a big thanks for this integration! I will monitor if not restarting HA while the inverter is offline solves the issue.

**Comment by krisdieteren** [comment]
Seems that indeed running a HA update while the inverter is offline causes the issue.
